import type { Dictionary } from './types'

export const en: Dictionary = {
  common: {
    appName: 'Telma',
    loading: 'Loading...',
    errorTitle: 'Something went wrong',
    errorGeneric: 'We could not complete the action. Please try again.',
    retry: 'Try again',
    save: 'Save',
    saving: 'Saving...',
    saved: 'Saved',
    cancel: 'Cancel',
    back: 'Back',
    search: 'Search',
    all: 'All',
    none: 'None',
    today: 'Today',
    signOut: 'Sign out',
    language: 'Language',
    copy: 'Copy',
    copied: 'Copied',
    patient: 'Patient',
    phone: 'Mobile',
    email: 'Email',
    name: 'Name',
    reason: 'Reason',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    actions: 'Actions',
    summary: 'Summary',
    of: 'of',
    thisMonth: 'this month',
    optional: 'optional',
  },
  status: {
    appointment: {
      pendente: 'To confirm',
      confirmada: 'Confirmed',
      rejeitada: 'Rejected',
      copiada: 'Copied to system',
    },
    clinic: { ativa: 'Active', pausada: 'Paused', cancelada: 'Cancelled' },
    call: {
      marcacao: 'Booking',
      transferida: 'Transferred',
      informacao: 'Information',
      nao_resolvida: 'Unresolved',
    },
    origin: { telefone: 'Phone', whatsapp: 'WhatsApp' },
  },
  plans: {
    essencial: 'Essencial',
    clinica: 'Clínica',
    rede: 'Rede',
    personalizado: 'Personalizado',
  },
  weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  auth: {
    title: 'Sign in',
    subtitle: 'Access your clinic dashboard.',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    invalid: 'Wrong email or password.',
  },
  clinicNav: {
    hoje: 'Today',
    marcacoes: 'Bookings',
    horarios: 'Hours',
    chamadas: 'Calls',
    conta: 'My clinic',
  },
  internoNav: {
    clinicas: 'Clinics',
    consumo: 'Usage',
    atividade: 'Activity',
  },
  hoje: {
    title: 'Today',
    greeting: 'Your clinic day with Telma.',
    live: 'Updating in real time',
    pendingTitle: 'To confirm',
    pendingEmpty: 'No bookings to confirm.',
    callsTitle: 'Calls today',
    callsEmpty: 'Telma has not answered any calls today yet.',
    seeAll: 'See all calls',
  },
  marcacoes: {
    title: 'Bookings',
    help: 'Telma leaves bookings here. Confirm each one and copy it into your clinic software.',
    empty: 'No bookings right now.',
    confirm: 'Confirm',
    alter: 'Change',
    reject: 'Reject',
    copyData: 'Copy patient details',
    copiedToSystem: 'Copied to clinic system',
    copiedToSystemHint: 'You can now copy this booking into your software.',
    alterWarning: 'When you change the date or time, the patient must be told.',
    newDateTime: 'New date and time',
    rejectReason: 'Reason (optional)',
    rejectReasonHint: 'Kept for the record, the patient is not told automatically.',
    confirmConfirm: 'Mark as confirmed',
    filterAll: 'All',
    filterPending: 'To confirm',
  },
  horarios: {
    title: 'Hours',
    help: 'Telma only offers these hours. She will never book outside them.',
    gridHint: 'Tap the hours you want to offer on each day.',
    capacityNote: 'Each hour takes one booking. Talk to us to change this.',
    blockedTitle: 'Blocked days',
    blockedHelp: 'Public holidays and time off. Telma books nothing on these days.',
    addBlock: 'Block a day',
    blockDayLabel: 'Day to block',
    blockReason: 'Reason',
    noBlocked: 'No blocked days.',
    remove: 'Remove',
    saving: 'Saving...',
  },
  chamadas: {
    title: 'Calls',
    filterResult: 'Result',
    filterFrom: 'From',
    filterTo: 'To',
    empty: 'No calls for these filters.',
    detail: 'Call detail',
    noSummary: 'No summary.',
    audio: 'Recording',
    noAudio: 'No recording available.',
    duration: 'Duration',
  },
  conta: {
    title: 'My clinic',
    clinicData: 'Clinic details',
    plan: 'Plan',
    addon: 'Telma on WhatsApp',
    addonOn: 'Active',
    addonOff: 'Not active',
    usageTitle: 'Usage this month',
    callsUsed: 'Calls used',
    limit: 'Plan limit',
    contactSupport: 'To change your plan or details, talk to us.',
  },
  interno: {
    clinicsTitle: 'Clinics',
    clinicsSubtitle: 'Every clinic and its usage this month.',
    searchPlaceholder: 'Search by name...',
    colName: 'Clinic',
    colPlan: 'Plan',
    colStatus: 'Status',
    colUsage: 'Calls / limit',
    colActivity: 'Last activity',
    overLimit: 'Over limit',
    nearLimit: 'Near limit',
    newClinic: 'New clinic',
    never: 'No activity',
    fichaData: 'Details',
    fichaTechnical: 'Technical config',
    assignedPhone: 'Assigned number',
    agentId: 'Voice agent id',
    voiceName: 'Voice',
    fichaSlots: 'Configured hours',
    fichaCalls: 'Recent calls',
    fichaAppointments: 'Recent bookings',
    openFicha: 'Open clinic',
    newTitle: 'New clinic',
    newHelp: 'Creates the clinic, its first user and the default hours.',
    fieldClinicName: 'Clinic name',
    fieldAddress: 'Address',
    fieldPhone: 'Clinic phone',
    fieldContactEmail: 'Contact email',
    fieldPlan: 'Plan',
    fieldAddon: 'Telma on WhatsApp',
    fieldUserEmail: 'Initial user email',
    fieldUserName: 'User name',
    fieldTempPassword: 'Temporary password',
    createClinic: 'Create clinic',
    creating: 'Creating...',
    createdOk: 'Clinic created.',
    defaultSlotsNote: 'Default hours: Monday to Friday, 9am to 1pm and 2pm to 6pm.',
    consumoTitle: 'Usage',
    consumoSubtitle: 'Minutes and calls across all clinics this month.',
    totalCalls: 'Calls',
    totalMinutes: 'Minutes',
    estimatedCost: 'Estimated cost',
    perClinic: 'Per clinic',
    atividadeTitle: 'Activity',
    atividadeSubtitle: 'Recent events across all clinics.',
    atividadeEmpty: 'No recent events.',
    eventTypes: {
      call_received: 'Call answered',
      appointment_created: 'Booking created',
      appointment_confirmed: 'Booking confirmed',
      appointment_rejected: 'Booking rejected',
      limit_warning: 'Near plan limit',
      clinic_created: 'Clinic created',
    },
  },
}
