import type { Dictionary } from './types'

export const pt: Dictionary = {
  common: {
    appName: 'Telma',
    loading: 'A carregar...',
    errorTitle: 'Algo correu mal',
    errorGeneric: 'Não foi possível completar a ação. Tente novamente.',
    retry: 'Tentar de novo',
    save: 'Guardar',
    saving: 'A guardar...',
    saved: 'Guardado',
    cancel: 'Cancelar',
    back: 'Voltar',
    search: 'Procurar',
    all: 'Todas',
    none: 'Nenhuma',
    today: 'Hoje',
    signOut: 'Sair',
    language: 'Idioma',
    copy: 'Copiar',
    copied: 'Copiado',
    patient: 'Paciente',
    phone: 'Telemóvel',
    email: 'Email',
    name: 'Nome',
    reason: 'Motivo',
    date: 'Data',
    time: 'Hora',
    status: 'Estado',
    actions: 'Ações',
    summary: 'Resumo',
    of: 'de',
    thisMonth: 'este mês',
    optional: 'opcional',
  },
  status: {
    appointment: {
      pendente: 'Por confirmar',
      confirmada: 'Confirmada',
      rejeitada: 'Rejeitada',
      copiada: 'Copiada para o sistema',
    },
    clinic: { ativa: 'Ativa', pausada: 'Pausada', cancelada: 'Cancelada' },
    call: {
      marcacao: 'Marcação',
      transferida: 'Transferida',
      informacao: 'Informação',
      nao_resolvida: 'Sem resolução',
    },
    origin: { telefone: 'Telefone', whatsapp: 'WhatsApp' },
  },
  plans: {
    essencial: 'Essencial',
    clinica: 'Clínica',
    rede: 'Rede',
    personalizado: 'Personalizado',
  },
  weekdays: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
  auth: {
    title: 'Entrar',
    subtitle: 'Aceda ao painel da sua clínica.',
    email: 'Email',
    password: 'Palavra-passe',
    signIn: 'Entrar',
    signingIn: 'A entrar...',
    invalid: 'Email ou palavra-passe incorretos.',
  },
  clinicNav: {
    hoje: 'Hoje',
    marcacoes: 'Marcações',
    horarios: 'Horários',
    chamadas: 'Chamadas',
    conta: 'A minha clínica',
  },
  internoNav: {
    clinicas: 'Clínicas',
    consumo: 'Consumo',
    atividade: 'Atividade',
  },
  hoje: {
    title: 'Hoje',
    greeting: 'O dia da sua clínica com a Telma.',
    live: 'A atualizar em tempo real',
    pendingTitle: 'Por confirmar',
    pendingEmpty: 'Não há marcações por confirmar.',
    callsTitle: 'Chamadas de hoje',
    callsEmpty: 'A Telma ainda não atendeu chamadas hoje.',
    seeAll: 'Ver todas as chamadas',
  },
  marcacoes: {
    title: 'Marcações',
    help: 'A Telma deixa aqui as marcações. Confirme e passe cada uma para o software da clínica.',
    empty: 'Não há marcações neste momento.',
    confirm: 'Confirmar',
    alter: 'Alterar',
    reject: 'Rejeitar',
    copyData: 'Copiar dados do paciente',
    copiedToSystem: 'Copiada para o sistema da clínica',
    copiedToSystemHint: 'Já pode passar esta marcação para o seu software.',
    alterWarning: 'Ao alterar a data ou a hora, é preciso avisar o paciente.',
    newDateTime: 'Nova data e hora',
    rejectReason: 'Motivo (opcional)',
    rejectReasonHint: 'Fica registado, o paciente não é avisado automaticamente.',
    confirmConfirm: 'Marcar como confirmada',
    filterAll: 'Todas',
    filterPending: 'Por confirmar',
  },
  horarios: {
    title: 'Horários',
    help: 'A Telma só oferece estes horários. Nunca vai marcar fora daqui.',
    gridHint: 'Toque nas horas que quer disponibilizar em cada dia.',
    capacityNote: 'Cada hora aceita uma marcação. Fale connosco para mudar.',
    blockedTitle: 'Dias bloqueados',
    blockedHelp: 'Feriados e férias. Nestes dias a Telma não marca nada.',
    addBlock: 'Bloquear dia',
    blockDayLabel: 'Dia a bloquear',
    blockReason: 'Motivo',
    noBlocked: 'Não há dias bloqueados.',
    remove: 'Remover',
    saving: 'A guardar...',
  },
  chamadas: {
    title: 'Chamadas',
    filterResult: 'Resultado',
    filterFrom: 'De',
    filterTo: 'Até',
    empty: 'Não há chamadas para estes filtros.',
    detail: 'Detalhe da chamada',
    noSummary: 'Sem resumo.',
    audio: 'Gravação',
    noAudio: 'Sem gravação disponível.',
    duration: 'Duração',
  },
  conta: {
    title: 'A minha clínica',
    clinicData: 'Dados da clínica',
    plan: 'Plano',
    addon: 'Telma no WhatsApp',
    addonOn: 'Ativo',
    addonOff: 'Não ativo',
    usageTitle: 'Consumo do mês',
    callsUsed: 'Chamadas usadas',
    limit: 'Limite do plano',
    contactSupport: 'Para mudar o plano ou os dados, fale connosco.',
  },
  interno: {
    clinicsTitle: 'Clínicas',
    clinicsSubtitle: 'Todas as clínicas e o seu consumo este mês.',
    searchPlaceholder: 'Procurar por nome...',
    colName: 'Clínica',
    colPlan: 'Plano',
    colStatus: 'Estado',
    colUsage: 'Chamadas / limite',
    colActivity: 'Última atividade',
    overLimit: 'Acima do limite',
    nearLimit: 'Perto do limite',
    newClinic: 'Nova clínica',
    never: 'Sem atividade',
    fichaData: 'Dados',
    fichaTechnical: 'Configuração técnica',
    assignedPhone: 'Número atribuído',
    agentId: 'Identificador do agente',
    voiceName: 'Voz',
    fichaSlots: 'Horários configurados',
    fichaCalls: 'Chamadas recentes',
    fichaAppointments: 'Marcações recentes',
    openFicha: 'Abrir ficha',
    newTitle: 'Nova clínica',
    newHelp: 'Cria a clínica, o primeiro utilizador e os horários por defeito.',
    fieldClinicName: 'Nome da clínica',
    fieldAddress: 'Morada',
    fieldPhone: 'Telefone da clínica',
    fieldContactEmail: 'Email de contacto',
    fieldPlan: 'Plano',
    fieldAddon: 'Telma no WhatsApp',
    fieldUserEmail: 'Email do utilizador inicial',
    fieldUserName: 'Nome do utilizador',
    fieldTempPassword: 'Palavra-passe provisória',
    createClinic: 'Criar clínica',
    creating: 'A criar...',
    createdOk: 'Clínica criada.',
    defaultSlotsNote: 'Horários por defeito: segunda a sexta, 9h às 13h e 14h às 18h.',
    consumoTitle: 'Consumo',
    consumoSubtitle: 'Minutos e chamadas de todas as clínicas este mês.',
    totalCalls: 'Chamadas',
    totalMinutes: 'Minutos',
    estimatedCost: 'Custo estimado',
    perClinic: 'Por clínica',
    atividadeTitle: 'Atividade',
    atividadeSubtitle: 'Eventos recentes de todas as clínicas.',
    atividadeEmpty: 'Sem eventos recentes.',
    eventTypes: {
      call_received: 'Chamada atendida',
      appointment_created: 'Marcação criada',
      appointment_confirmed: 'Marcação confirmada',
      appointment_rejected: 'Marcação rejeitada',
      limit_warning: 'Perto do limite do plano',
      clinic_created: 'Clínica criada',
    },
  },
}
