import type { Content } from '@/content'
import { Section, SectionHeader } from '@/components/ui/Section'
import { Reveal } from '@/components/ui/Reveal'
import { Figure } from '@/components/ui/Figure'

/**
 * Control. This section answers one fear — "do I lose command of my own diary?"
 * — so it is the calmest block on the page: a photograph, two paragraphs,
 * nothing to click.
 *
 * The composition is deliberately off-balance. The image takes seven of twelve
 * columns starting hard at the left edge, the text takes four starting at
 * column nine, and the text block is pushed a long way down so the two halves
 * never line up at the top. After three sections that begin on the same
 * baseline, the drop is what makes the eye move.
 */
export function Agenda({ c }: { c: Content }) {
  return (
    <Section id="agenda" tone="bg" rule>
      {/* Aligned on the bottom edge, not the top. The offset is the point of
          this section — after three blocks that all start on the same baseline,
          the drop is what makes the eye move — but it has to be generated by
          the content rather than pushed with a fixed padding.

          It used to be `pt-32`. That put the foot of the text 12px below the
          foot of the photograph in Spanish and Portuguese and 14px above it in
          English: neither edge aligned, both nearly did, and the sign flipped
          with the language. A near-miss always reads as a mistake.

          Anchored at the bottom, the two columns close on an exact shared line
          in every language, and the ragged top is unmistakably deliberate. */}
      <div className="grid grid-cols-1 gap-16 lg:grid-cols-12 lg:items-end lg:gap-x-10">
        <Reveal className="lg:col-span-7">
          <Figure slot="hands-agenda" sizes="(max-width: 1024px) 100vw, 58vw" />
        </Reveal>

        <Reveal delay={120} className="lg:col-span-5 lg:col-start-8 lg:pb-2">
          <SectionHeader eyebrow={c.agenda.label} title={c.agenda.title} />
          <div className="mt-10 flex flex-col gap-6">
            {c.agenda.paragraphs.map((p, i) => (
              <p key={i} className="leading-relaxed text-ink-soft">
                {p}
              </p>
            ))}
          </div>
        </Reveal>
      </div>
    </Section>
  )
}
